### ISSUE TITLE
Optimization for blocks filter out used at very first bridge run

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-nodejs#7] opened 2018-05-20 15:10 UTC
At the current implementation the number of blocks which needs to be used to look for bridge events could be several millions even if the bridge contracts were deployed recently:

https://github.com/poanetwork/bridge-nodejs/blob/a23ecb78572f3e1928d9129eff8d4118b2618b57/src/processCollectedSignatures.js#L51

`db.processedBlock` is taken from the bridge database and equals `0` during very first start.

At the same time every bridge contract contain the number of block which contract deployment transaction was included in:
* Home: https://github.com/poanetwork/poa-bridge-contracts/blob/3b33b2855f89849bce5a49fd417669468c665d41/contracts/upgradeable_contracts/U_HomeBridge.sol#L31
* Foreign: https://github.com/poanetwork/poa-bridge-contracts/blob/3b33b2855f89849bce5a49fd417669468c665d41/contracts/upgradeable_contracts/U_ForeignBridge.sol#L43

This block number could be used as the initial position to look for bridge event.

It is necessary to change the database initialization process:
https://github.com/poanetwork/bridge-nodejs/blob/a23ecb78572f3e1928d9129eff8d4118b2618b57/src/processDeposits.js#L24-L25
https://github.com/poanetwork/bridge-nodejs/blob/a23ecb78572f3e1928d9129eff8d4118b2618b57/src/processCollectedSignatures.js#L32-L33
https://github.com/poanetwork/bridge-nodejs/blob/a23ecb78572f3e1928d9129eff8d4118b2618b57/src/processWithdraw.js#L32-L33
as so if the initial value is zero the method `deployedAtBlock()` of the corresponding contract needs to be called.

**Comment by rstormsf** [comment] 2018-05-22 22:39
hmmm.... I checked the difference is very insignificant between 0 block or deployedAtBlock
we only do it once and we go from there. 
but sure, it's probably good enhancement

**Comment by akolotov** [comment] 2018-06-18 06:18
it needs to be addressed on deployment-playbook side since the starting block depends on the moment when deployment of particular validator happens: either it is very first run of the bridge or adding of a new validator to existing bridge.

as soon as @phahulin will answer regarding the repo to deploy `bridge-nodejs` and the corresponding issue is created there, #7 could be closed.

**Comment by phahulin** [comment] 2018-06-18 09:11
The same repository can be used (new deployment will be in a different folder) https://github.com/poanetwork/deployment-bridge
so that all deployment scripts will be in one place

**Comment by fvictorio** [comment] 2018-07-04 16:33
Do we need to do something in the bridge side for this? From what I understand from @akolotov's comment, at the very least we should support specifying the starting block with an environment variable. Am I missing something here?

**Comment by phahulin** [comment] 2018-07-04 16:51
Yes, env variable would be good.

I was thinking - what if we add a script that gets deployment block number into this very repository and  ansible will call it during deployment? The reason is that this repo already has abis, contract addresses, rpc endpoints, etc and npm dependencies, so it would be inconvenient to have similar functionality duplicated in multiple places. @akolotov what do you think?

**Comment by fvictorio** [comment] 2018-07-04 17:07
I'm not sure it's a good idea.

- The repo doesn't have contract addresses (yet). They are passed with env variables.
- It does have ABIs, but I think it's a problem and something we should improve (be it with submodules, exposing truffle artifacts through npm, moving the contracts code to this repo, or some other option)

**Comment by phahulin** [comment] 2018-07-04 20:39
This is how deployment for rust version of the bridge works now:
1. there are bridge-specific parameters, shared by all validators (including contract addresses) - these options are preset in the ansible config for each bridge [see here](https://github.com/poanetwork/deployment-bridge/blob/master/upgradable-wo-parity/group_vars/core-foundation.yml)
2. there are validator-specific parameters (like private keys, ip address) [see template here](https://github.com/poanetwork/deployment-bridge/blob/master/upgradable-wo-parity/hosts.yml.template)
3. validator provides required parameters from 2. and starts the ansible deployment
4. ansible combines all parameters and creates configuration files
5. ansible downloads other files required by the bridge and starts it

So I was thinking about using a similar approach here as well.
```
bridge parameters set in the ansible config for the bridge
+
validator parameters
--------
.env file

so at this moment contract addresses are known from .env
=> then this new script runs and calls `deployedAtBlock()` to get initial block numbers
=> and adds them to .env
=> now env is fully set
=> starts docker container with the bridge
```

However, I might miss something here, so I'd appreciate your opinion on this @fvictorio

**Comment by fvictorio** [comment] 2018-07-06 02:17
@phahulin From what I understand of what @akolotov is saying, the issue is with a new validator being added. Let's say that the bridge has N validators working for a time, and then a N+1 validator is added. This new validator shouldn't start listening from the block where the contract was deployed; it should start listening from when it was added to the contract. At least that's what I understand, please let me know if I'm wrong.

If this is the case, one option is to get the block where it was added. I see that there is a `ValidatorAdded(address)` event in the `BridgeValidators` contract. We could use this event, get its block and start listening after that. (And I think that event should have the address indexed for this to work.)

**Comment by phahulin** [comment] 2018-07-06 13:42
@fvictorio good catch. Yes, it's one part of the issue, it might also be necessary in some other cases to start processing from arbitrary block number. We had a discussion with @akolotov about this, and come up with the following:
1. There will be an option in deployment scripts to directly set the required block number. If this option is set, deployment script will add special env variable (let's call it `START_BLOCK` here) for the bridge
2. If block number is not set in deployment config, deployment script will call a new js script from this repo and use it's output as `START_BLOCK`. The script should be smth like:
```
try {
        call deployedAtBlock()
        get past events starting from deployedAtBlock and look for ValidatorAdded event for current validator
        if (event found) {
            return that event's block number
        }
        else {
            return deployedAtBlock
        }
}
catch () {
        return 0
}
```
3. when starting, bridge gets first block number in database from `lastProcessedBlock`. If this value is not set, bridge should use `START_BLOCK`, unless `START_BLOCK` is also not set, in which case bridge defaults to `0`.

Does it make sense?

**Comment by phahulin** [comment] 2018-07-06 17:58
Yes, please. Thank you :+1:

**Closed** 2018-07-25 20:42 UTC
Labels: low priority, review
